class InformationDetection < BaseTrain
  COLUMNS = [:information_detection_pii_paragraphs, :information_detection_pii_sentences, :information_detection_pii_phrases, 
:information_detection_pii_tokens, :information_detection_pii_entities, :information_detection_pii_knowledge, 
:information_detection_pii_extractions, :information_detection_pii_extra_data, :information_detection_writeprint_paragraphs, 
:information_detection_writeprint_sentences, :information_detection_writeprint_phrases, :information_detection_writeprint_tokens, 
:information_detection_writeprint_entities, :information_detection_writeprint_knowledge, :information_detection_writeprint_extractions, 
:information_detection_writeprint_extra_data, :information_detection_temporal_information_paragraphs, :information_detection_temporal_information_sentences, 
:information_detection_temporal_information_phrases, :information_detection_temporal_information_tokens, :information_detection_temporal_information_entities, 
:information_detection_temporal_information_knowledge, :information_detection_temporal_information_extractions, :information_detection_temporal_information_extra_data,
:information_detection_esg_sentiment_extractions, :information_detection_esg_sentiment_categories, :information_detection_hate_speech_extractions, 
:information_detection_hate_speech_categories]
  COLUMNS.each {|column| attr_accessor column }

  def persist!

  end
end